export enum BufferUsage {
    STATIC_DRAW = WebGL2RenderingContext.STATIC_DRAW,
    DYNAMIC_DRAW = WebGL2RenderingContext.DYNAMIC_DRAW,
    STREAM_DRAW = WebGL2RenderingContext.STREAM_DRAW,
    STATIC_READ = WebGL2RenderingContext.STATIC_READ,
    DYNAMIC_READ = WebGL2RenderingContext.DYNAMIC_READ,
    STREAM_READ = WebGL2RenderingContext.STREAM_READ,
    STATIC_COPY = WebGL2RenderingContext.STATIC_COPY,
    DYNAMIC_COPY = WebGL2RenderingContext.DYNAMIC_COPY,
    STREAM_COPY = WebGL2RenderingContext.STREAM_COPY
}

export enum BufferTarget {
    ARRAY_BUFFER = WebGL2RenderingContext.ARRAY_BUFFER,
    ELEMENT_ARRAY_BUFFER = WebGL2RenderingContext.ELEMENT_ARRAY_BUFFER,
    COPY_READ_BUFFER = WebGL2RenderingContext.COPY_READ_BUFFER,
    COPY_WRITE_BUFFER = WebGL2RenderingContext.COPY_WRITE_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER = WebGL2RenderingContext.TRANSFORM_FEEDBACK_BUFFER,
    UNIFORM_BUFFER = WebGL2RenderingContext.UNIFORM_BUFFER,
    PIXEL_PACK_BUFFER = WebGL2RenderingContext.PIXEL_PACK_BUFFER,
    PIXEL_UNPACK_BUFFER = WebGL2RenderingContext.PIXEL_UNPACK_BUFFER
}
